### ISSUE TITLE
Left-side navigation is lost when opening the website directly via URL

### ISSUE THREAD

**Issue by kyon45** [web-infra-dev/rspack-website#215]
**How to Reproduce?**
Open any browser, type "https://www.rspack.dev/zh/config/devserver" in the address bar, and the left-side navigation flickers and then disappears

**OS & Browser Version**
- macOS: 13.2.1 (22D68)
- Microsoft Edge: 110.0.1587.63

**Comment by h-a-n-a** [comment]
@sanyuan0704 Could you take a look into this?

**Comment by sanyuan0704** [comment]
I will fix it.

**Comment by sanyuan0704** [comment]
We have updated the website.Now you can use the url: https://www.rspack.dev/zh/guide/dev-server and the left-side navigation will not lost.
