### ISSUE TITLE
Ability to use mailto links

### ISSUE THREAD

**Issue by ulivz** [web-infra-dev/rspack-website#229]
# Summary

Parsed result of [mailto links](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_an_email_address) will be prefixed with `/` so it will doesn't work and always jump to 404
 
# Reproduction

## Case 1

- Input:

```md
✉️ [web-infra-careers@bytedance.com](mailto:web-infra-careers@bytedance.com)
```

- Output:

![image](https://user-images.githubusercontent.com/23133919/224587711-85e9a48a-b263-44f4-a92a-263bec5bb8dd.png)

## Case 2

- Input:

```md
<a href="mailto:web-infra-careers@bytedance.com">web-infra-careers@bytedance.com</a>
```

- Output:

![image](https://user-images.githubusercontent.com/23133919/224587834-86b74b0f-006f-4da4-82a8-6b3bca825265.png)

**Comment by sanyuan0704** [comment]
I will work for this
