### ISSUE TITLE
[Bug Report]: https://www.rspack.dev/ layouts overflow

### ISSUE THREAD

**Issue by 4n70w4** [web-infra-dev/rspack-website#231]
### System Info

nope

### Details

see on tail of letter G — tip cut off:
![image](https://user-images.githubusercontent.com/38257723/224635777-5a79881c-6155-4dfe-ac91-660bb91525d9.png)

but in selected text all ok:
![image](https://user-images.githubusercontent.com/38257723/224635870-924eddcd-377a-4a9e-9a58-30e82b86f7e8.png)

### Reproduce Steps

open site https://www.rspack.dev/

**Comment by 4n70w4** [comment]
chrome 111.0.5563.65

![image](https://user-images.githubusercontent.com/38257723/224785119-a55e55e2-32c1-444d-9f9f-63b47088dfde.png)

![image](https://user-images.githubusercontent.com/38257723/224785229-a40d21f0-8848-4b0a-9c74-3cbf76b38766.png)
![image](https://user-images.githubusercontent.com/38257723/224785346-79d569ad-042b-4a46-bc40-201d523efd78.png)

**Comment by sanyuan0704** [comment]
Thanks, i will fix it

**Comment by hardfist** [comment]
@sanyuan0704 is it fixed?

**Comment by sanyuan0704** [comment]
yes, it is normal in chrome now.
