### ISSUE TITLE
Add partnership chapter to describe the relationships with the partner of Rspack

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack-website#253]
I have seen some people misunderstand the relationship between Mordern.js and Rspack. We should make declarations for all Rspack's partners.

**Comment by hyf0** [comment]
@hardfist. You may assign this issue to others if there are more appropriate persons.

**Comment by hardfist** [comment]
@hyf0 what misunderstanding do you see

**Comment by hyf0** [comment]
> @hyf0 what misunderstanding do you see

I couldn't find the related information. Feel free to close this issue.
