### ISSUE TITLE
Dark Mode | Navbar Group items are not visible. 

### ISSUE THREAD

**Issue by ShashankSuresh** [web-infra-dev/rspack-website#275]
**Steps to reproduce:**
1. Go to https://www.rspack.dev/.
2. Enable "dark" mode.
3. Hover on the Navbar items such as "About", "Ecosystem" or "Language" and you will see there is a white background applied. 

**Screenshots:** 
[HoverIssue.pdf](https://github.com/web-infra-dev/rspack-website/files/11200622/HoverIssue.pdf)
[HoverIssue2.pdf](https://github.com/web-infra-dev/rspack-website/files/11200623/HoverIssue2.pdf)

**Note:**
It's an easy fix if Im able to run the local dev environment. Since this website uses Modern.js any help here would be highly appreciated.

**Comment by hyf0** [comment]
@sanyuan0704 cc

**Comment by sanyuan0704** [comment]
![image](https://user-images.githubusercontent.com/39261479/231930029-4deb9dce-851f-46c4-b8fd-8165e30e2320.png)
I cannot see the white background and i have fix the style problem before.Would you clear the cache and visit the page again?
