### ISSUE TITLE
Incorrect external link href in the navigation menu

### ISSUE THREAD

**Issue by HydratedPig** [web-infra-dev/rspack-website#309]
When switching the language to Chinese, **the external links** in the navigation menu will incorrectly append `/zh` to their `href`, which is suspected to be a version issue of `@modern-js/doc-tools`. This problem does not exist in `modern.js`.

语言切换成中文时，导航菜单**外链**的 `href` 会错误地拼上 `/zh`，目测是 `@modern-js/doc-tools` 的版本问题，`modern.js` 那没有这个问题

![image](https://github.com/web-infra-dev/rspack-website/assets/40666766/6d91df97-ba75-485a-80f0-7406a0749631)

**Comment by hardfist** [comment]
fixed
