### ISSUE TITLE
docs for feat(splitChunks): support passing RegExp to splitChunks.chunks

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack-website#375]
https://github.com/web-infra-dev/rspack/pull/3473

**Comment by hyf0** [comment]
Closes for that the docs is already finished.

https://github.com/web-infra-dev/rspack-website/blob/524f08cc67e0176c69cd847e8aa75e7d27d85043/docs/en/config/optimization-split-chunks.mdx#L220
