### ISSUE TITLE
site redirect issue to unsupported language

### ISSUE THREAD

**Issue by maartentibau** [web-infra-dev/rspack-website#394]
I visited the Rspack website for the first time (no cookies, localstorage, etc...) and I noticed an auto-redirect to `/nl/` route which is not supported and results in a 404.

Made a small screen recording.

https://github.com/web-infra-dev/rspack-website/assets/4103756/d337124b-be39-4e83-92a9-ac96b425d904

Was looking around in the source code to see if I could find some logic that executes this behaviour, but sadly I did not.
If you can point me in the right direction I gladly would create a PR.

**Comment by hardfist** [comment]
this should be fixed, feel free to reopen if it's not fixed
