### ISSUE TITLE
list all supported top 100 used community plugins and loaders

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack-website#511]
we can list the top 100 used loaders and plugins and check whether these plugin are supported, so our compatible page looks more promising

**Comment by bvanjoi** [comment]
I propose the following actions:
1. Establish a repository named ﻿`rspack-compat`, serving as a comprehensive list of compatible loaders and plugins within the Webpack ecosystem.
2. Include this repository in our ecosystem's ci to guarantee successful execution.
3. Feature this collection of loaders and plugins on our website for increased visibility and ease of access.

**Comment by hardfist** [comment]
> I propose the following actions:
> 
> 1. Establish a repository named ﻿`rspack-compat`, serving as a comprehensive list of compatible loaders and plugins within the Webpack ecosystem.
> 2. Include this repository in our ecosystem's ci to guarantee successful execution.
> 3. Feature this collection of loaders and plugins on our website for increased visibility and ease of access.

That's a good idea

**Comment by bvanjoi** [comment]
We can further discuss this topic at https://github.com/web-infra-dev/rspack-compat.
