### ISSUE TITLE
move builtins.{emotion,relay,pluginImport} description into builtin:swc-loader page

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack-website#557]
since we already deprecate builtins.{emotion,relay,pluginImport}, we shouldn't redirect the options explanation to this deprecated page

**Comment by hardfist** [comment]
related to https://github.com/getsentry/sentry/pull/61475#discussion_r1421211972

**Comment by h-a-n-a** [comment]
added in 0.5.0
