### ISSUE TITLE
Looks like migration guide has errors in code snippet

### ISSUE THREAD

**Issue by krutoo** [web-infra-dev/rspack-website#608]
On this page:
https://www.rspack.dev/blog/announcing-0.4.html#deprecating-default-transformation

There is code snippet, in this snippet "transform" property is on same level as "jsc" property but is should be inside "jsc" object

**Comment by hardfist** [comment]
thanks, are you willing to fix it for us

**Comment by krutoo** [comment]
@hardfist yes later

**Comment by krutoo** [comment]
@hardfist Here is some fixes https://github.com/web-infra-dev/rspack-website/pull/609

**Comment by krutoo** [comment]
close because PR was merged
